### ISSUE TITLE
Gauge become line chart

### ISSUE THREAD

**Issue by mafen** [ciknowles/mqtt-cogs#13]
`[mqttcogs_drawgoogle options="{height:200}"
	charttype="Gauge" 
	ajax="true"]
		[mqttcogs_data limit="10" topics="weather/outTemp_C"]
[/mqttcogs_drawgoogle]`

I use this piece of code to try to get a gauge like shown on your webpage but it only comes up as a line chart

http://mqttcogs.sailresults.org/examples/making-gauge-chart/ is the page i looked at

**Comment by ciknowles** [comment]
Hi,

Try setting the limit="1" and let me know how you get on. 

You need to have a single piece of data for the gauge chart.

Chris
