### ISSUE TITLE
Error someotherWTFFFFFF!!!!

### ISSUE THREAD

**Issue by TheDarkBlueEvil** [ciknowles/mqtt-cogs#14]
I get this error in de Mqtt  Cogs log. 

- Connection would be etablished
- blocking mode: ON
- connect 
- write is also ok 
- but after socked_read(2) the log shows Error someotherWTFFFFFF

In SQL it shows the follow: 

ERROR  array (
  'type' => 8,
  'message' => 'fwrite(): send of 2 bytes failed with errno=32 Broken pipe',
  'file' => '/var/www/vhosts/agrarnet.at/httpdocs/wp-content/plugins/mqtt-cogs-master/sskaje/mqtt/SocketClient.php',
  'line' => 166,
)

I don´t know exactly where is the issue..

**Comment by ciknowles** [comment]
Did you get this sorted? This is normally related to ports not being opened. 

Chris

**Comment by TheDarkBlueEvil** [comment]
Hi, 

thanks for the answer. It was a problem with SSL. Now it works. But I had troubles with ERROR wp forced disconnect. I think this is the point with the cron job, but I don’t know exactly what there is to do. 

By the way, thanks for the plug-in, it’s great for me.

**Comment by ciknowles** [comment]
Hi,

Great.

Yes, you'll be right about the forced disconnect.

A php page will have a default timeout after which it is killed. 
Mqttcogs has a setting to disconnect and reconnect every n seconds. This 
is best done via a proper cron job as wordpress cron jobs don't work 
very well.

 From this page http://mqttcogs.sailresults.org/get-started-with-mqttcogs/

MqttCogs sets up a scheduled event that runs every minute in WordPress. 
When the event fires MqttCogs checks if still connected. If not it 
reconnects to the Mqtt broker. However, WordPress scheduled events are a 
little flaky. Have a read of this article about how to properly set up 
wordpress cron jobs!

Chris

**Comment by TheDarkBlueEvil** [comment]
Hi, 

i have read it. But no luck with it. 

*	I have installed wordpress on a plesk inviroment. 
*	Than deactivadet „define('DISABLE_WP_CRON', true);“ in wp-config.php
*	After that i habe setup the cron

Maybe you have an idea? 


BR

**Comment by ciknowles** [comment]
Hi,

Do you know what the timeout is for your php scripts on your server?

You need to set the Mqtt recycle setting to less than this.

Chris

**Comment by TheDarkBlueEvil** [comment]
Hi, 

no i don´t know the timeout. 
But the question is, is the cron job ok is there somthing else to do…

BR Stefan

**Comment by ciknowles** [comment]
Hi Stefan,

Are you using the wordpress Cron job or did you disable it and use a 
server cron job?

 From uk. Am a developer, use a lot of languages. Php is more of a hobby.

Chris

**Comment by TheDarkBlueEvil** [comment]
Hi, 

i do exactly this: 
*	I have installed wordpress on a plesk inviroment.
*	Than deactivadet the cron job in Wordpres --> „define('DISABLE_WP_CRON', true);“ at wp-config.php
*	After that i setup the cron in Plesk like this: 
BR

**Comment by ciknowles** [comment]
Ha,

I am getting this error "ERROR wp forced disconnect" now.

Why because CloudMqtt have shut down their free 'Cute Cat' tier mqtt 
service. Will have to find another.

Chris

**Comment by TheDarkBlueEvil** [comment]
I have set the MQTT Connection Recycle to „280“

Now that is my log:

**Comment by ciknowles** [comment]
Hi,

What MQTT broker are you using?

Have you checked that you can access it from your wordpress server?

C

**Comment by TheDarkBlueEvil** [comment]
Hi, 

 i´m using Mosquitto and yes, i can connect and get values from it into my wordpress. 
It looks like only the cronjob won´t work. Because every 280sec (what i have set in the MQTT Cogs Settings) i get the „ERROR wp forced disconnect“

 

BR Stefan

**Comment by ciknowles** [comment]
Hi,

Try setting it to 58secs. Then enable/disable the plugin and see if that 
helps.

Chris

**Comment by TheDarkBlueEvil** [comment]
Hi, 


it gets worse when i do so.
There is 58secs:
There is 280sec:

**Comment by ciknowles** [comment]
Hi,

Can you send me the last 100 lines or so of your debug log and I'll look 
at what is going on.

(make sure you blank any sensitive stuff if you are posting to github)

The debug you've already sent is being removed by github - can't tell 
much from that.

Chris

**Comment by TheDarkBlueEvil** [comment]
Hi, 

here are the last 100 entrys from MQTT Log (MQTT  Debug --> ALL)

Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) |  
-- | --
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | NOTICE loop(): Connection lost.
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG keepalive(): current_time=1638952960, last_ping_time=1638952833, keepalive=60
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG ping()
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message write: message_type=PINGREQ
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message Build: total length=2
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) |  
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | NOTICE loop(): Connection lost.
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG keepalive(): current_time=1638952960, last_ping_time=1638952833, keepalive=60
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG ping()
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message write: message_type=PINGREQ
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message Build: total length=2
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) |  
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | NOTICE loop(): Connection lost.
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG keepalive(): current_time=1638952960, last_ping_time=1638952833, keepalive=60
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG ping()
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message write: message_type=PINGREQ
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message Build: total length=2
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) |  
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | NOTICE loop(): Connection lost.
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG keepalive(): current_time=1638952960, last_ping_time=1638952833, keepalive=60
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG ping()
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message write: message_type=PINGREQ
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message Build: total length=2
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) |  
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | NOTICE loop(): Connection lost.
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG keepalive(): current_time=1638952960, last_ping_time=1638952833, keepalive=60
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG ping()
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message write: message_type=PINGREQ
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message Build: total length=2
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) |  
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | NOTICE loop(): Connection lost.
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG keepalive(): current_time=1638952960, last_ping_time=1638952833, keepalive=60
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG ping()
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message write: message_type=PINGREQ
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message Build: total length=2
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) |  
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | NOTICE loop(): Connection lost.
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG keepalive(): current_time=1638952960, last_ping_time=1638952833, keepalive=60
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG ping()
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message write: message_type=PINGREQ
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message Build: total length=2
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) |  
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | NOTICE loop(): Connection lost.
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG keepalive(): current_time=1638952960, last_ping_time=1638952833, keepalive=60
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG ping()
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message write: message_type=PINGREQ
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message Build: total length=2
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) |  
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | NOTICE loop(): Connection lost.
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG keepalive(): current_time=1638952960, last_ping_time=1638952833, keepalive=60
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG ping()
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message write: message_type=PINGREQ
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message Build: total length=2
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) |  
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | NOTICE loop(): Connection lost.
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG keepalive(): current_time=1638952960, last_ping_time=1638952833, keepalive=60
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG ping()
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message write: message_type=PINGREQ
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message Build: total length=2
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) |  
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | NOTICE loop(): Connection lost.
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG keepalive(): current_time=1638952960, last_ping_time=1638952833, keepalive=60
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG ping()
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message write: message_type=PINGREQ
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message Build: total length=2
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) |  
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | NOTICE loop(): Connection lost.
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG keepalive(): current_time=1638952960, last_ping_time=1638952833, keepalive=60
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG ping()
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message write: message_type=PINGREQ
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message Build: total length=2
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) |  
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | NOTICE loop(): Connection lost.
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG keepalive(): current_time=1638952960, last_ping_time=1638952833, keepalive=60
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG ping()
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message write: message_type=PINGREQ
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message Build: total length=2
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) |  
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | NOTICE loop(): Connection lost.
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG keepalive(): current_time=1638952960, last_ping_time=1638952833, keepalive=60
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG ping()
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message write: message_type=PINGREQ
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message Build: total length=2
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) |  
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | NOTICE loop(): Connection lost.
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG keepalive(): current_time=1638952960, last_ping_time=1638952833, keepalive=60
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG ping()
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message write: message_type=PINGREQ
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message Build: total length=2
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) |  
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | NOTICE loop(): Connection lost.
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG keepalive(): current_time=1638952960, last_ping_time=1638952833, keepalive=60
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG ping()
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message write: message_type=PINGREQ
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message Build: total length=2
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) |  
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | NOTICE loop(): Connection lost.
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) |  
Wed Dec 08 2021 09:42:40 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG keepalive(): current_time=1638952960, last_ping_time=1638952833, keepalive=60

But values are transmitting

**Comment by ciknowles** [comment]
Ok,

So it is failing because it is not getting the expected response after a 
ping.

What protocol does your mqtt broker use?

In fact, if you tell me what broker you are using I could try it.

Chris

**Comment by TheDarkBlueEvil** [comment]
mosquitto version 2.0.14

**Comment by ciknowles** [comment]
What do you have your protocol set to in the mqttcogs settings?

try 3_1_1

Chris

**Comment by TheDarkBlueEvil** [comment]
ok actually i tried this before. 
I changed it again. 

The log now shows the following


Wed Dec 08 2021 10:51:31 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG loop(): received PINGRESP
Wed Dec 08 2021 10:52:01 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG keepalive(): current_time=1638957121, last_ping_time=1638957091, keepalive=60
Wed Dec 08 2021 10:52:01 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG ping()
Wed Dec 08 2021 10:52:01 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message write: message_type=PINGREQ
Wed Dec 08 2021 10:52:01 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message Build: total length=2
Wed Dec 08 2021 10:52:01 GMT+0100 (Mitteleuropäische Normalzeit) |  
Wed Dec 08 2021 10:52:01 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG socket_read(2)
Wed Dec 08 2021 10:52:01 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG message_read(): message_type=PINGRESP, flags=0
Wed Dec 08 2021 10:52:01 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG message_read(): remaining length=0, data to read=0
Wed Dec 08 2021 10:52:01 GMT+0100 (Mitteleuropäische Normalzeit) |  
Wed Dec 08 2021 10:52:01 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG loop(): received PINGRESP
Wed Dec 08 2021 10:52:01 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG checking
Wed Dec 08 2021 10:52:01 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG somethingLock is not acqiured
Wed Dec 08 2021 10:52:31 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG keepalive(): current_time=1638957151, last_ping_time=1638957121, keepalive=60
Wed Dec 08 2021 10:52:31 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG ping()
Wed Dec 08 2021 10:52:31 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message write: message_type=PINGREQ
Wed Dec 08 2021 10:52:31 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message Build: total length=2
Wed Dec 08 2021 10:52:31 GMT+0100 (Mitteleuropäische Normalzeit) |  
Wed Dec 08 2021 10:52:31 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG socket_read(2)
Wed Dec 08 2021 10:52:31 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG message_read(): message_type=PINGRESP, flags=0
Wed Dec 08 2021 10:52:31 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG message_read(): remaining length=0, data to read=0
Wed Dec 08 2021 10:52:31 GMT+0100 (Mitteleuropäische Normalzeit) |  
Wed Dec 08 2021 10:52:31 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG loop(): received PINGRESP
Wed Dec 08 2021 10:52:34 GMT+0100 (Mitteleuropäische Normalzeit) |  
Wed Dec 08 2021 10:52:35 GMT+0100 (Mitteleuropäische Normalzeit)

**Comment by ciknowles** [comment]
Now working I think.

C

**Comment by TheDarkBlueEvil** [comment]
I think so. Thanks for your time. 

BR

**Comment by TheDarkBlueEvil** [comment]
After some time (nothing change) my log looks like this: 

Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) | NOTICE loop(): Connection lost.
-- | --
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG keepalive(): current_time=1638982538, last_ping_time=1638982383, keepalive=60
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG ping()
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message write: message_type=PINGREQ
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message Build: total length=2
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) |  
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) | NOTICE loop(): Connection lost.
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG keepalive(): current_time=1638982538, last_ping_time=1638982383, keepalive=60
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG ping()
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message write: message_type=PINGREQ
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message Build: total length=2
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) |  
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) | NOTICE loop(): Connection lost.
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG keepalive(): current_time=1638982538, last_ping_time=1638982383, keepalive=60
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG ping()
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message write: message_type=PINGREQ
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message Build: total length=2
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) |  
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) | NOTICE loop(): Connection lost.
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG keepalive(): current_time=1638982538, last_ping_time=1638982383, keepalive=60
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG ping()
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message write: message_type=PINGREQ
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message Build: total length=2
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) |  
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) | NOTICE loop(): Connection lost.
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG keepalive(): current_time=1638982538, last_ping_time=1638982383, keepalive=60
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG ping()
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message write: message_type=PINGREQ
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message Build: total length=2
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) |  
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) |  
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message write: message_type=PINGREQ
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message Build: total length=2
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) |  
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) | NOTICE loop(): Connection lost.
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG keepalive(): current_time=1638982538, last_ping_time=1638982383, keepalive=60
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG ping()
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message write: message_type=PINGREQ
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message Build: total length=2
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) |  
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) | NOTICE loop(): Connection lost.
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG keepalive(): current_time=1638982538, last_ping_time=1638982383, keepalive=60
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG ping()
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message write: message_type=PINGREQ
Wed Dec 08 2021 17:55:38 GMT+0100 (Mitteleuropäische Normalzeit) | DEBUG Message Build: total length=2

**Comment by ciknowles** [comment]
Apart from all the datetimes being the same (this is odd). This looks normal. Trying turning off Debug level logging (your log will get big very quickly) and check it is working as expected.
