### ISSUE TITLE
mysql 8 support

### ISSUE THREAD

**Issue by TheGer** [ciknowles/mqtt-cogs#16]
Hello!  Do you have plans to implement mysql 8 support?  I'm getting some issues with queries and blank date strings.

**Comment by ciknowles** [comment]
Hi,

Hadn't realised there was problem. Could you post some errors into the 
ticket?

Thanks

Chris

**Comment by TheGer** [comment]
Sure, it's related to empty string comparison in this set of queries.  I'm attaching a partial fix that doesn't take dates into account, but I'm working on fixing it properly by setting a default value for the date.  

The query SELECT `topic` as topic,`utc` as dtm,(`payload`) as payload from wp_s3zggf_mqttcogs_plugin_data
									WHERE topic LIKE ''
									AND ((utc>='' OR ''='') 
									AND (utc<='' OR ''='')) 
									AND `payload` IS NOT NULL
									order by utc DESC limit 100
returns an error due to datetime string comparison.

[MqttCogs_Plugin.php.txt](https://github.com/ciknowles/mqtt-cogs/files/8664617/MqttCogs_Plugin.php.txt)

**Comment by TheGer** [comment]
https://bugs.mysql.com/bug.php?id=93513

**Comment by TheGer** [comment]
AM actually thinking perhaps just removing the AND...s if there are no datetime values included would probably do the trick.  Thanks for the great plugin btw

**Comment by ciknowles** [comment]
Hmm,

Just swapping around the values in the OR might do it? It would work in 
other languages as the statements after the first in the OR wouldn't be 
evaluated?

''='' OR utc>=''

Chris

**Comment by TheGer** [comment]
it worked!  Thank you very much.
