### ISSUE TITLE
Fatal Error on WP 6.2.2 PHP 8

### ISSUE THREAD

**Issue by rafalszm** [ciknowles/mqtt-cogs#17]
Hi, i trying install this plugin. I have crytical php 8.0 issue on new clean WP 6.2.2. 
Details bellow.
`Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, bool given in /home/local/domains/testdomain.com/public_html/logger/wp-content/plugins/mqtt-cogs-master/MqttCogs_Plugin.php:97 Stack trace: #0 /home/local/domains/testdomain.com/public_html/logger/wp-content/plugins/mqtt-cogs-master/MqttCogs_LifeCycle.php(29): MqttCogs_Plugin->initOptions() #1 /home/local/domains/testdomain.com/public_html/logger/wp-content/plugins/mqtt-cogs-master/mqtt-cogs_init.php(34): MqttCogs_LifeCycle->install() #2 /home/local/domains/testdomain.com/public_html/logger/wp-content/plugins/mqtt-cogs-master/mqtt-cogs.php(100): MqttCogs_init('/home/local/do...') #3 /home/local/domains/testdomain.com/public_html/logger/wp-admin/includes/plugin.php(2314): include_once('/home/local/do...') #4 /home/local/domains/testdomain.com/public_html/logger/wp-admin/plugins.php(192): plugin_sandbox_scrape('mqtt-cogs-maste...') #5 {main} thrown in /home/local/domains/testdomain.com/public_html/logger/wp-content/plugins/mqtt-cogs-master/MqttCogs_Plugin.php on line 97`

**Comment by ciknowles** [comment]
Hi, 

I have just released a new version that fixes this issue on php 8. 

C
